services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: it-asset-management:latest
    container_name: it-asset-management-app
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb:27017/it-asset-management
      - JWT_SECRET=super_secret_jwt_key_123456_asset_manager
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7-jammy
    container_name: it-asset-management-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
